[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["graphql"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "graphql"
  org = "wso2shashika"
  version = "1.0.1"

